on:
  issue_comment:
    types: [created]
jobs:
  get-comment:
    runs-on: ubuntu-latest
    env:
      COMMENT: ${{ github.event.issue.body }}
    steps:
      - name: "Getting Comments"
        run: |
          echo $COMMENT
